In [ ]:
import pandas as pd
import numpy as np
import spacy
import re
import math

In [ ]:
df = pd.read_excel('/content/llm.xlsx')

In [ ]:
df.head()

,text_before,text_after
0,"ТО подлежат МИ, включая изделия, которые наход...",ТО подлежат медицинские изделия: \n● находящие...
1,Испытательное давление для стальных трубопрово...,Испытательные давления для стальных трубопрово...
2,Если техническое обслуживание выполняется собс...,В случае исполнения работ по ТО собственной сл...
3,"После ремонта средства измерений (МИ), который...","Должен быть проведен КТС (либо поверка, в случ..."
4,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО ме...

In [ ]:
def count_syllables_ru(word):
    vowels = "аеёиоуыэюя"
    count = 0
    word = word.lower()
    for char in word:
        if char in vowels:
            count += 1
    return max(1, count)

def fres_ru(text):
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    num_sentences = len(sentences)

    words = re.findall(r'\b\w+\b', text.lower())
    num_words = len(words)

    num_syllables = sum(count_syllables_ru(word) for word in words)

    if num_words == 0 or num_sentences == 0:
        return 0.0

    words_per_sentence = num_words / num_sentences
    syllables_per_word = num_syllables / num_words

    fres = 206.835 - 1.3 * words_per_sentence - 60.1 * syllables_per_word
    return fres

In [ ]:
df['FRESru_before'] = df['text_before'].apply(fres_ru)
df['FRESru_after'] = df['text_after'].apply(fres_ru)

display(df.head())

,text_before,text_after,FRESru_before,FRESru_after
0,"ТО подлежат МИ, включая изделия, которые наход...",ТО подлежат медицинские изделия: \n● находящие...,-13.651667,-46.613361
1,Испытательное давление для стальных трубопрово...,Испытательные давления для стальных трубопрово...,46.923000,48.895870
2,Если техническое обслуживание выполняется собс...,В случае исполнения работ по ТО собственной сл...,-31.169237,-14.148766
3,"После ремонта средства измерений (МИ), который...","Должен быть проведен КТС (либо поверка, в случ...",-53.906176,-5.737109
4,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО ме...,-19.523929,-46.116266

In [ ]:
def fkgl_ru(text):
    """Calculates Flesch-Kincaid Grade Level score for Russian text."""
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    num_sentences = len(sentences)

    words = re.findall(r'\b\w+\b', text.lower())
    num_words = len(words)

    num_syllables = sum(count_syllables_ru(word) for word in words)

    if num_words == 0 or num_sentences == 0:
        return 0.0  # Handle cases with no words or sentences

    asl = num_words / num_sentences  # Average Sentence Length
    asw = num_syllables / num_words  # Average Syllables per Word

    fkgl = 0.5 * asl + 8.4 * asw - 15.59
    return fkgl

df['FKGLru_before'] = df['text_before'].apply(fkgl_ru)
df['FKGLru_after'] = df['text_after'].apply(fkgl_ru)

display(df.head())

,text_before,text_after,FRESru_before,FRESru_after,FKGLru_before,FKGLru_after
0,"ТО подлежат МИ, включая изделия, которые наход...",ТО подлежат медицинские изделия: \n● находящие...,-13.651667,-46.613361,22.123333,29.541967
1,Испытательное давление для стальных трубопрово...,Испытательные давления для стальных трубопрово...,46.923000,48.895870,14.718000,13.805652
2,Если техническое обслуживание выполняется собс...,В случае исполнения работ по ТО собственной сл...,-31.169237,-14.148766,27.065085,27.550909
3,"После ремонта средства измерений (МИ), который...","Должен быть проведен КТС (либо поверка, в случ...",-53.906176,-5.737109,37.086471,19.319524
4,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО ме...,-19.523929,-46.116266,24.960000,32.337215

In [ ]:
def smog_ru(text):
    """Calculates SMOG readability index for Russian text."""
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    num_sentences = len(sentences)

    words = re.findall(r'\b\w+\b', text.lower())
    num_words = len(words)

    multi_syllable_words_count = sum(1 for word in words if count_syllables_ru(word) >= 4)

    if num_sentences == 0:
        return 0.0

    sentences_in_tens = num_sentences / 10

    if num_sentences == 0:
        return 0.0
    try:
        smog = 1.1 * np.sqrt(multi_syllable_words_count * (64.6 / num_sentences) + 0.05)
        return smog
    except ZeroDivisionError:
        return 0.0
    except ValueError:
        return 0.0


df['SMOGru_before'] = df['text_before'].apply(smog_ru)
df['SMOGru_after'] = df['text_after'].apply(smog_ru)

display(df.head())

,text_before,text_after,FRESru_before,FRESru_after,FKGLru_before,FKGLru_after,SMOGru_before,SMOGru_after
0,"ТО подлежат МИ, включая изделия, которые наход...",ТО подлежат медицинские изделия: \n● находящие...,-13.651667,-46.613361,22.123333,29.541967,27.011291,35.365470
1,Испытательное давление для стальных трубопрово...,Испытательные давления для стальных трубопрово...,46.923000,48.895870,14.718000,13.805652,19.770951,19.770951
2,Если техническое обслуживание выполняется собс...,В случае исполнения работ по ТО собственной сл...,-31.169237,-14.148766,27.065085,27.550909,32.485404,33.081483
3,"После ремонта средства измерений (МИ), который...","Должен быть проведен КТС (либо поверка, в случ...",-53.906176,-5.737109,37.086471,19.319524,40.516003,22.829086
4,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО ме...,-19.523929,-46.116266,24.960000,32.337215,28.649668,36.986018

In [ ]:
def count_characters_digits(text):
    """Counts letters and digits in a string."""
    return sum(c.isalnum() for c in text)

def count_words(text):
    """Counts words in a string."""
    words = re.findall(r'\b\w+\b', text)
    return len(words)

def count_sentences(text):
    """Counts sentences in a string."""
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    return len(sentences)

def ariru(text):
    """Calculates Automated Readability Index (ARI) for Russian text."""
    num_chars_digits = count_characters_digits(text)
    num_words = count_words(text)
    num_sentences = count_sentences(text)

    if num_words == 0 or num_sentences == 0:
        return 0.0 # Handle cases with no words or sentences

    ari = 6.26 * (num_chars_digits / num_words) + 0.2805 * (num_words / num_sentences) - 31.04
    return ari

def cliru(text):
    """Calculates Coleman-Liau Index (CLI) for Russian text."""
    num_chars_digits = count_characters_digits(text)
    num_words = count_words(text)
    num_sentences = count_sentences(text)

    if num_words == 0:
        return 0.0 # Handle cases with no words

    L = (num_chars_digits / num_words) * 100 # Average number of characters per 100 words
    S = (num_sentences / num_words) * 100 # Average number of sentences per 100 words

    cli = 0.055 * L - 0.35 * S - 20.33
    return cli

df['ARIru_before'] = df['text_before'].apply(ariru)
df['ARIru_after'] = df['text_after'].apply(ariru)
df['CLIru_before'] = df['text_before'].apply(cliru)
df['CLIru_after'] = df['text_after'].apply(cliru)

display(df.head())

,text_before,text_after,FRESru_before,FRESru_after,FKGLru_before,FKGLru_after,SMOGru_before,SMOGru_after,ARIru_before,ARIru_after,CLIru_before,CLIru_after
0,"ТО подлежат МИ, включая изделия, которые наход...",ТО подлежат медицинские изделия: \n● находящие...,-13.651667,-46.613361,22.123333,29.541967,27.011291,35.365470,19.627962,26.876889,17.231538,21.891311
1,Испытательное давление для стальных трубопрово...,Испытательные давления для стальных трубопрово...,46.923000,48.895870,14.718000,13.805652,19.770951,19.770951,5.269300,4.261935,4.010000,3.496087
2,Если техническое обслуживание выполняется собс...,В случае исполнения работ по ТО собственной сл...,-31.169237,-14.148766,27.065085,27.550909,32.485404,33.081483,25.617123,20.083406,20.992034,14.189481
3,"После ремонта средства измерений (МИ), который...","Должен быть проведен КТС (либо поверка, в случ...",-53.906176,-5.737109,37.086471,19.319524,40.516003,22.829086,31.136088,19.788847,21.042549,18.159796
4,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО ме...,-19.523929,-46.116266,24.960000,32.337215,28.649668,36.986018,21.528286,26.157725,17.705714,19.302911

In [ ]:
def ti_ru(text):
    """Calculates the TI readability index for Russian text."""
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    num_sentences = len(sentences)

    words = re.findall(r'\b\w+\b', text.lower())
    num_words = len(words)

    num_syllables = sum(count_syllables_ru(word) for word in words)

    if num_words == 0 or num_sentences == 0:
        return 0.0 # Handle cases with no words or sentences

    asl = num_words / num_sentences  # Average Sentence Length
    asw = num_syllables / num_words  # Average Syllables per Word

    if asl <= 1:
        return 0.0
    ti = asw * math.log10(asl)
    return ti

def lix_ru(text):
    """Calculates the LIX readability index for Russian text."""
    sentences = re.split(r'[.!?]+', text)
    sentences = [s.strip() for s in sentences if s.strip()]
    num_sentences = len(sentences)

    words = re.findall(r'\b\w+\b', text) # Keep original case to count letters
    num_words = len(words)

    # Count words longer than 6 letters
    long_words_count = sum(1 for word in words if len(word) > 6)

    if num_words == 0 or num_sentences == 0:
        return 0.0 # Handle cases with no words or sentences

    # LIX(d) = A/B + 100 * C/A
    # A = number of words, B = number of sentences, C = number of words longer than 6 letters
    lix = (num_words / num_sentences) + 100 * (long_words_count / num_words)
    return lix


df['TIru_before'] = df['text_before'].apply(ti_ru)
df['TIru_after'] = df['text_after'].apply(ti_ru)
df['LIXru_before'] = df['text_before'].apply(lix_ru)
df['LIXru_after'] = df['text_after'].apply(lix_ru)

display(df.head())

,text_before,text_after,FRESru_before,FRESru_after,FKGLru_before,FKGLru_after,SMOGru_before,SMOGru_after,ARIru_before,ARIru_after,CLIru_before,CLIru_after,TIru_before,TIru_after,LIXru_before,LIXru_after
0,"ТО подлежат МИ, включая изделия, которые наход...",ТО подлежат медицинские изделия: \n● находящие...,-13.651667,-46.613361,22.123333,29.541967,27.011291,35.365470,19.627962,26.876889,17.231538,21.891311,4.274535,5.280214,77.051282,94.434426
1,Испытательное давление для стальных трубопрово...,Испытательные давления для стальных трубопрово...,46.923000,48.895870,14.718000,13.805652,19.770951,19.770951,5.269300,4.261935,4.010000,3.496087,2.963633,2.901072,49.000000,49.086957
2,Если техническое обслуживание выполняется собс...,В случае исполнения работ по ТО собственной сл...,-31.169237,-14.148766,27.065085,27.550909,32.485404,33.081483,25.617123,20.083406,20.992034,14.189481,4.882799,4.509297,88.822034,83.954545
3,"После ремонта средства измерений (МИ), который...","Должен быть проведен КТС (либо поверка, в случ...",-53.906176,-5.737109,37.086471,19.319524,40.516003,22.829086,31.136088,19.788847,21.042549,18.159796,5.524492,3.862034,113.745098,69.394558
4,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО ме...,-19.523929,-46.116266,24.960000,32.337215,28.649668,36.986018,21.528286,26.157725,17.705714,19.302911,4.574053,5.355674,90.500000,100.259494

In [ ]:
import spacy
import re
import math

# Download the spaCy model for Russian
try:
    nlp = spacy.load('ru_core_news_sm')
except OSError:
    print("Downloading spaCy model 'ru_core_news_sm'...")
    from spacy.cli import download
    download('ru_core_news_sm')
    nlp = spacy.load('ru_core_news_sm')

In [ ]:
def calculate_dd_mdd(text):
    # Удаление символов '●'
    cleaned_text = text.replace('●', '')
    doc = nlp(cleaned_text)
    dd_list = []
    for token in doc:
        # пропускаем корень предложения (у него head == self)
        if token.head.i != token.i:
            dd = abs(token.head.i - token.i)
            dd_list.append(dd)
    mdd = sum(dd_list) / len(dd_list) if dd_list else 0
    total_dd = sum(dd_list) if dd_list else 0
    return dd_list, mdd, total_dd

def add_dependency_metrics(df, text_col):
    dd_results = []
    mdd_results = []
    tdd_results = []
    for text in df[text_col]:
        dd, mdd, tdd = calculate_dd_mdd(text)
        dd_results.append(dd)
        mdd_results.append(mdd)
        tdd_results.append(tdd)
    df['DD'+text_col] = dd_results
    df['MDD'+text_col] = mdd_results
    df['TotalDD'+text_col] = tdd_results
    return df

df = add_dependency_metrics(df, 'text_before')
df = add_dependency_metrics(df, 'text_after')

In [ ]:
df

,text_before,text_after,FRESru_before,FRESru_after,FKGLru_before,FKGLru_after,SMOGru_before,SMOGru_after,ARIru_before,ARIru_after,...,TIru_before,TIru_after,LIXru_before,LIXru_after,DDtext_before,MDDtext_before,TotalDDtext_before,DDtext_after,MDDtext_after,TotalDDtext_after
0,"ТО подлежат МИ, включая изделия, которые наход...",ТО подлежат медицинские изделия: \n● находящие...,-13.651667,-46.613361,22.123333,29.541967,27.011291,35.365470,19.627962,26.876889,...,4.274535,5.280214,77.051282,94.434426,"[1, 1, 1, 2, 1, 2, 1, 3, 1, 2, 2, 1, 11, 2, 1,...",4.162162,308,"[1, 1, 2, 2, 1, 3, 1, 2, 2, 1, 10, 2, 1, 3, 2,...",4.123457,334
1,Испытательное давление для стальных трубопрово...,Испытательные давления для стальных трубопрово...,46.923000,48.895870,14.718000,13.805652,19.770951,19.770951,5.269300,4.261935,...,2.963633,2.901072,49.000000,49.086957,"[1, 11, 2, 1, 3, 1, 5, 1, 2, 1, 1, 5, 1, 1, 2,...",3.000000,84,"[1, 11, 2, 1, 3, 1, 5, 1, 2, 1, 4, 5, 3, 1, 1,...",2.518519,68
2,Если техническое обслуживание выполняется собс...,В случае исполнения работ по ТО собственной сл...,-31.169237,-14.148766,27.065085,27.550909,32.485404,33.081483,25.617123,20.083406,...,4.882799,4.509297,88.822034,83.954545,"[3, 1, 1, 8, 1, 2, 1, 2, 3, 1, 1, 1, 1, 1, 2, ...",3.884058,268,"[1, 11, 1, 1, 1, 2, 1, 6, 1, 1, 2, 1, 1, 2, 3,...",4.542553,427
3,"После ремонта средства измерений (МИ), который...","Должен быть проведен КТС (либо поверка, в случ...",-53.906176,-5.737109,37.086471,19.319524,40.516003,22.829086,31.136088,19.788847,...,5.524492,3.862034,113.745098,69.394558,"[1, 15, 14, 1, 1, 2, 1, 2, 1, 6, 1, 3, 2, 1, 4...",4.081967,249,"[1, 2, 1, 2, 1, 3, 5, 4, 1, 2, 1, 6, 1, 2, 1, ...",2.833333,170
4,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО ме...,-19.523929,-46.116266,24.960000,32.337215,28.649668,36.986018,21.528286,26.157725,...,4.574053,5.355674,90.500000,100.259494,"[8, 1, 1, 1, 1, 2, 1, 4, 1, 1, 2, 1, 4, 3, 1, ...",2.868852,175,"[7, 1, 1, 1, 3, 1, 2, 2, 1, 3, 4, 1, 2, 1, 5, ...",3.511111,316
5,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО в ...,-45.947353,-67.870072,30.562941,27.685362,31.878182,28.421397,29.129353,34.500130,...,5.315133,5.026068,101.647059,100.115942,"[9, 1, 1, 1, 1, 2, 2, 1, 6, 1, 2, 1, 2, 4, 1, ...",3.384615,132,"[8, 1, 1, 1, 4, 2, 1, 1, 1, 1, 2, 1, 5, 1, 2, ...",3.065574,187
6,"Прибор, установку или оборудование, подготовле...",Необходимо проверить перед включением: \n● при...,-45.841923,-73.092273,23.863846,30.537273,23.392787,31.878182,25.575731,31.755545,...,4.370085,5.613768,74.538462,85.636364,"[12, 1, 2, 1, 4, 1, 2, 1, 1, 2, 3, 5, 1, 1, 2, 4]",2.687500,43,"[1, 1, 2, 2, 1, 3, 2, 1, 3, 1, 1, 2, 1, 4, 2, ...",1.964286,55
7,"Растворы щелочей, концентрированных кислот и а...",Приготавливать растворы разрешается только:\n●...,7.613125,22.795215,17.347500,13.421828,17.684018,13.507325,17.072375,17.899790,...,3.574731,2.879134,75.375000,78.075269,"[7, 1, 2, 1, 3, 1, 5, 1, 3, 2, 1, 4, 2, 1, 3, ...",2.970588,101,"[2, 1, 4, 3, 1, 1, 5, 1, 1, 2, 1, 5, 2, 1, 3, ...",2.585366,106
8,Легковоспламеняющиеся и горючие жидкости необх...,ЛВЖ и ГЖ должны храниться: \n● в лабораторных ...,-20.389000,11.575000,24.126000,21.250000,26.524602,23.392787,21.294900,15.978333,...,4.529326,3.840515,93.000000,73.333333,"[3, 1, 2, 1, 1, 1, 2, 3, 2, 1, 6, 1, 2, 1, 2, ...",2.777778,75,"[3, 1, 2, 1, 4, 1, 2, 1, 26, 1, 1, 3, 7, 1, 5,...",4.589744,179
9,Основным источником травм при работе со стекля...,"Основным травмирующим фактором, связанным с ис...",-1.279286,-21.828636,22.410000,26.873636,25.007769,27.959265,17.280429,22.795288,...,4.134737,4.693589,78.000000,93.606061,"[1, 11, 1, 1, 3, 2, 1, 3, 1, 2, 1, 4, 1, 2, 1,...",2.677419,83,"[2, 1, 12, 1, 2, 1, 2, 1, 2, 1, 2, 1, 4, 9, 3,...",3.075000,123
10,"Чтобы избежать ожогов кистей и пальцев, посуду...",Следует переносить посуду с горячей жидкостью:...,25.385000,39.739505,17.410000,11.690180,17.684018,15.315303,13.252000,7.949230,...,3.450528,2.742446,65.666667,47.468468,"[1, 10, 1, 1, 1, 2, 5, 4, 2, 1, 3, 1, 1, 2, 1,...",2.964286,83,"[1, 1, 2, 1, 3, 4, 1, 2, 1, 5, 1, 1, 2, 1, 1, ...",3.081633,151
11,При получении травмы или любом несчастном случ...,При получении травмы и при каждом несчастном с...,-52.491866,-20.206250,41.981642,28.875000,40.516003,30.627643,28.677082,22.122000,...,5.232931,4.666000,108.791045,85.000000,"[1, 9, 1, 3, 2, 1, 5, 3, 1, 2, 1, 2, 1, 2, 1, ...",4.054054,300,"[1, 11, 1, 9, 3, 2, 1, 5, 4, 1, 2, 1, 1, 2, 3,...",2.723404,256
12,"Проверить состояние спецодежды, спецобуви и др...",Выполнить: \n● Проверить исправность спецодежд...,19.776212,23.027857,12.655455,12.010000,13.698865,12.944461,16.907664,19.828714,...,2.433797,2.278872,58.115152,72.666667,"[1, 1, 1, 2, 2, 1, 5, 1, 2, 1, 11, 1, 13, 1, 2...",2.666667,96,"[2, 1, 3, 1, 1, 1, 2, 1, 2, 10, 1, 1, 1, 1, 3,...",2.169811,115
13,"Все работы, связанные с использованием или воз...",Выполнять все операции:\n● только в вытяжном ш...,-0.763649,-15.752121,19.314054,20.188788,22.541950,22.829086,18.984385,20.450818,...,3.870011,3.949622,80.662162,82.848485,"[1, 20, 1, 2, 1, 2, 2, 1, 3, 5, 1, 2, 1, 4, 6,...",3.250000,143,"[1, 2, 5, 1, 3, 2, 1, 6, 1, 3, 2, 1, 5, 1, 1, ...",2.910448,195
14,Под периодом индивидуальных испытаний (далее —...,Под периодом индивидуальных испытаний (именуем...,-65.269762,-125.455667,35.810000,54.726000,40.516003,60.612396,29.628619,45.085500,...,5.874616,7.325239,108.666667,151.000000,"[1, 9, 1, 2, 4, 3, 1, 1, 5, 1, 1, 1, 2, 3, 1, ...",2.860000,143,"[1, 10, 1, 2, 5, 4, 1, 2, 1, 6, 1, 1, 2, 1, 3,...",3.882353,396
15,Объем и условия выполнения пусконаладочных раб...,Объем и условия выполнения пусконаладочных раб...,-73.367222,-51.132949,37.896667,32.879231,44.206453,40.030782,34.583833,32.066167,...,6.098517,5.487133,113.888889,104.384615,"[27, 1, 2, 1, 1, 2, 1, 7, 1, 1, 1, 2, 1, 6, 13...",3.629630,196,"[6, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 3, 1, ...",2.805825,289
16,Если в рабочей документации нет дополнительных...,Величину испытательного давления на прочность ...,-12.212619,-17.158478,21.710000,19.377391,25.007769,21.657712,21.353357,23.082272,...,4.218509,3.689384,87.666667,85.413043,"[4, 2, 1, 1, 15, 1, 2, 1, 11, 1, 2, 1, 2, 1, 2...",2.666667,64,"[12, 1, 2, 1, 2, 1, 6, 1, 2, 2, 1, 3, 1, 3, 1,...",2.615385,68
17,Работы по проведению общего опробования включа...,Работы по проведению комплексного опробования ...,-39.797609,-92.120556,33.523043,51.976667,33.081483,43.313329,25.410826,37.355315,...,5.169008,6.149563,100.347826,136.555556,"[5, 1, 2, 1, 2, 1, 1, 2, 1, 4, 1, 2, 1, 2, 1, ...",3.280000,164,"[5, 1, 2, 1, 2, 2, 1, 3, 1, 2, 1, 2, 2, 1, 3, ...",3.406250,327
18,Звуковой и световой сигнал подает система мони...,Система мониторинга: \n● выдает: \n● звук \n● ...,-10.790926,-32.108478,23.421111,25.127391,27.959265,29.323821,18.730537,24.947152,...,4.347105,4.736445,89.962963,92.565217,"[3, 1, 2, 1, 1, 1, 3, 2, 1, 5, 1, 2, 1, 1, 3, ...",3.033333,91,"[14, 1, 2, 1, 10, 2, 1, 7, 1, 1, 4, 1, 1, 1, 1...",2.687500,86
19,"Не используйте растворители, автомобильные мою...",Не используйте для очистки холодильника: \n● р...,-35.525000,-39.286053,24.650000,24.857368,29.323821,29.323821,26.215000,27.664237,...,4.683708,4.711197,90.000000,92.684211,"[1, 1, 3, 2, 1, 4, 1, 6, 2, 1, 9, 3, 2, 1, 13,...",4.888889,132,"[1, 1, 2, 1, 2, 1, 6, 1, 2, 1, 4, 1, 6, 1, 1, ...",2.857143,80
20,При подключении системы к внешним сервисам чер...,В случае интеграции системы с внешними сервиса...,20.699286,-52.417308,17.110000,41.334615,18.756532,37.510645,15.689548,31.012500,...,3.494437,5.271394,80.523810,128.076923,"[1, 8, 1, 2, 1, 4, 1, 6, 1, 1, 1, 2, 1, 1, 2, ...",2.837209,122,"[1, 9, 1, 1, 2, 1, 3, 1, 6, 1, 2, 1, 27, 1, 2,...",3.042254,216
21,Если технические условия распространяются на п...,Если ТУ распространяются на продукты двух и бо...,-25.465000,-42.657308,29.610000,31.694615,30.627643,31.878182,22.122000,25.806167,...,4.806180,5.262752,90.000000,90.282051,"[3, 1, 1, 15, 1, 2, 3, 1, 2, 4, 3, 1, 1, 4, 1,...",3.814815,206,"[2, 1, 15, 1, 2, 3, 1, 2, 4, 3, 1, 1, 4, 1, 2,...",4.034483,234
22,Показатели могут отличаться от указанных в зав...,Значения отличаются от приведенных значений в ...,-21.200294,-45.929865,27.104118,31.515405,34.242525,38.538481,21.212294,28.064986,...,4.684524,5.340363,92.823529,104.567568,"[1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 6, 1, ...",3.925000,157,"[1, 2, 1, 3, 1, 5, 3, 2, 1, 4, 1, 1, 3, 1, 1, ...",2.687500,129
23,После завершения уборки робот-пылесос возвраща...,"После того, как: \n● робот-пылесос закончит уб...",7.881000,-1.793571,16.196000,24.710000,18.756532,19.770951,15.034250,19.378071,...,3.334606,4.191042,64.500000,80.714286,"[1, 5, 1, 3, 2, 1, 2, 1, 3, 1, 2, 6, 2, 1, 1, ...",2.740741,74,"[1, 14, 7, 6, 5, 1, 3, 2, 1, 8, 1, 1, 2, 3, 4,...",3.489362,164
24,"Гарантия не действует для котлов, в конструкци...",Гарантия не распространяется на котлы (кроме с...,-33.573824,-40.906935,28.833529,28.903548,31.878182,34.242525,25.999353,27.937435,...,4.999828,5.147603,92.823529,95.516129,"[2, 1, 1, 2, 5, 1, 3, 1, 1, 6, 1, 2, 1, 4, 1, ...",3.325000,133,"[2, 1, 1, 2, 2, 1, 3, 1, 1, 2, 1, 1, 2, 7, 1, ...",2.410256,94
25,Гарантия не распространяется на повреждения ко...,Гарантия не распространяется: \n● на дефекты к...,-49.909681,-67.037222,35.254681,39.876667,42.401397,46.783635,29.559670,32.911815,...,5.443212,5.870890,106.574468,120.666667,"[2, 1, 1, 2, 1, 1, 3, 4, 3, 2, 1, 5, 2, 1, 3, ...",3.900000,234,"[2, 1, 3, 1, 1, 4, 1, 1, 3, 3, 1, 1, 11, 1, 1,...",3.106667,233
26,Контроль качества на всех этапах производства ...,Контроль качества на всех этапах производства ...,-60.074091,-59.349091,32.219091,35.619091,34.242525,34.242525,31.521348,34.227455,...,5.659916,5.714733,99.666667,123.545455,"[6, 1, 2, 1, 4, 1, 1, 2, 3, 1, 2, 4, 1, 6, 1, ...",4.184211,159,"[6, 1, 2, 1, 4, 1, 2, 1, 3, 1, 2, 1, 4, 1, 2, ...",4.571429,256
27,При выполнении инвазивных процедур необходимо ...,При проведении инвазивных процедур строго собл...,-18.680625,-65.047759,21.022500,31.641034,25.007769,37.510645,22.941125,34.513810,...,4.101534,5.698309,84.750000,108.310345,"[1, 3, 1, 2, 1, 2, 1, 1, 1, 2, 7, 1, 1, 1, 2, ...",2.800000,98,"[1, 4, 1, 2, 1, 1, 1, 1, 2, 1, 5, 2, 1, 3, 1, ...",3.538462,138
28,Для технологии MIMO (Multiple Input Multiple O...,Для MIMO (Multiple Input Multiple Output) важн...,-36.128636,-37.494545,32.373636,32.564545,34.242525,35.365470,30.955182,32.520182,...,5.079763,5.117114,100.818182,103.090909,"[1, 8, 1, 1, 2, 1, 2, 3, 4, 1, 1, 2, 1, 4, 3, ...",5.500000,341,"[1, 7, 1, 2, 1, 2, 3, 4, 1, 2, 1, 3, 1, 4, 3, ...",4.703125,301
29,Исследование стабильности бактериальных штаммо...,Исследование стабильности бактериальных штаммо...,-20.255541,-46.012143,22.038378,25.320000,26.524602,27.959265,25.582764,29.851036,...,4.280986,4.759060,83.364865,91.785714,"[10, 1, 1, 2, 1, 2, 1, 2, 1, 4, 1, 1, 1, 2, 1,...",2.675000,107,"[10, 1, 1, 2, 1, 2, 1, 2, 1, 4, 2, 1, 3, 1, 1,...",2.837209,122
30,Для стабильной передачи данных в распределённы...,Для обеспечения устойчивой передачи данных в р...,4.109324,-17.143947,18.632973,21.762632,23.392787,27.251376,18.815196,22.557395,...,3.767267,4.240078,75.256757,79.526316,"[2, 1, 5, 1, 2, 1, 4, 1, 1, 1, 1, 4, 1, 1, 2, ...",2.675000,107,"[1, 7, 1, 2, 1, 2, 1, 4, 2, 1, 3, 1, 1, 2, 1, ...",2.764706,141
31,Наличие источников тепла рядом с местом устано...,"Наличие источников, излучающих тепло в непосре...",-10.773000,-21.527069,22.782000,25.558276,27.959265,31.878182,18.540500,22.209672,...,4.305655,4.639332,73.000000,91.068966,"[26, 1, 1, 23, 1, 2, 1, 2, 1, 3, 2, 1, 3, 2, 1...",4.633333,139,"[13, 1, 1, 2, 1, 2, 1, 4, 1, 2, 1, 8, 1, 1, 2,...",2.685714,94
32,Для безопасной работы оборудования при превыше...,Для обеспечения безопасности работы оборудован...,-25.197000,-44.518333,24.798000,29.090000,29.323821,35.365470,22.046100,25.159667,...,4.641161,5.219162,93.000000,93.333333,"[2, 1, 12, 1, 1, 9, 1, 1, 2, 1, 2, 1, 1, 3, 1,...",2.769231,72,"[1, 4, 1, 1, 1, 1, 2, 1, 2, 2, 1, 3, 1, 2, 1, ...",3.031250,97
33,"Нажмите кнопку питания, чтобы включить аэрофри...","Нажмите кнопку питания, чтобы включить аэрофри...",51.097500,61.478605,9.360000,8.147791,13.981255,13.981255,6.664500,4.148863,...,2.375000,2.254707,52.500000,47.959302,"[1, 1, 2, 1, 5, 1, 7, 1, 1, 1, 1, 2, 1, 2, 3, ...",2.660377,141,"[1, 1, 2, 1, 5, 1, 2, 1, 4, 10, 1, 1, 2, 1, 2,...",3.224138,187
34,При подготовке рабочей документации следует уч...,При составлении рабочей документации необходим...,-26.967500,-76.410902,29.820000,43.414918,34.242525,47.611705,23.530500,33.790172,...,4.846231,6.058414,92.500000,123.295082,"[1, 3, 1, 2, 1, 1, 1, 2, 2, 1, 6, 1, 2, 1, 10,...",3.372093,145,"[1, 3, 1, 2, 2, 1, 3, 1, 1, 2, 2, 1, 6, 1, 1, ...",3.679487,287
35,"Чтобы повысить удобство работы с устройством, ...","Чтобы улучшить взаимодействие с пользователем,...",12.201129,10.262419,16.547097,16.818065,18.756532,19.770951,15.916137,18.339363,...,3.455802,3.494200,73.564516,76.790323,"[1, 13, 1, 1, 1, 2, 2, 1, 6, 1, 2, 1, 2, 1, 1,...",2.971429,104,"[1, 5, 1, 1, 2, 4, 1, 1, 1, 3, 2, 1, 3, 1, 1, ...",3.225000,129
36,В режиме ожидания поверните регулятор и выбери...,В режиме ожидания поверните головку регулятора...,17.029697,1.563571,15.606970,15.010000,18.405973,14.179520,12.768091,14.612048,...,3.313442,2.556783,64.666667,65.523810,"[1, 2, 1, 1, 1, 3, 1, 2, 6, 1, 2, 1, 4, 1, 2, ...",2.833333,136,"[1, 2, 1, 1, 1, 3, 1, 1, 2, 1, 1, 2, 3, 1, 1, ...",2.000000,102
37,Фактические значения могут отличаться от указа...,Значения отличаются от приведенных значений в ...,-20.265000,-37.853571,27.610000,29.750000,34.242525,36.453841,20.965222,26.353500,...,4.668908,5.117483,97.111111,100.714286,"[1, 1, 1, 1, 2, 1, 2, 1, 4, 1, 2, 1, 2, 1, 2, ...",3.809524,160,"[1, 2, 1, 3, 1, 5, 3, 2, 1, 4, 1, 1, 2, 1, 1, ...",2.826087,130
38,Чтобы очистить внутреннюю поверхность аэрофрит...,Для удаления пятен с внутренней стороны аэрофр...,37.085000,16.519762,12.910000,14.723333,12.505699,16.931307,13.440167,14.621643,...,2.940228,3.109388,71.666667,68.809524,"[1, 7, 1, 2, 1, 1, 5, 6, 1, 1, 2, 2, 1, 5, 1, ...",3.031250,97,"[1, 6, 1, 2, 1, 3, 1, 2, 1, 3, 1, 5, 1, 2, 1, ...",2.641026,103
39,Если вы планируете использовать баллоны со сжи...,Кухонную плиту не следует устанавливать: \n● е...,39.845000,1.175541,13.320000,24.931622,16.542113,25.007769,8.388179,17.575257,...,2.983291,4.111232,54.642857,85.648649,"[2, 1, 8, 1, 1, 2, 1, 3, 6, 1, 1, 1, 2, 2, 1, ...",2.684211,102,"[1, 2, 1, 1, 4, 1, 2, 1, 5, 1, 1, 2, 1, 3, 1, ...",2.977273,131
40,Ножной тормоз должен обеспечивать полный возвр...,Работа ножного тормоза должна обеспечивать пол...,19.268333,-6.721667,17.310000,21.420000,21.657712,25.007769,12.708595,17.421917,...,3.525918,4.146693,68.619048,78.055556,"[1, 1, 1, 1, 2, 1, 2, 1, 6, 1, 8, 1, 10, 1, 2,...",3.066667,138,"[3, 1, 2, 1, 1, 2, 1, 4, 1, 2, 1, 6, 1, 1, 3, ...",2.698113,143
41,Когда в баке заканчивается резервный запас или...,При каждом включении зажигания на панели прибо...,1.744677,-16.538684,22.942258,27.725789,25.007769,30.627643,17.234855,21.297421,...,4.089218,4.573058,76.161290,82.736842,"[3, 1, 1, 20, 1, 2, 2, 1, 5, 1, 2, 1, 1, 2, 1,...",2.718750,87,"[2, 1, 6, 1, 1, 2, 1, 1, 1, 1, 1, 1, 4, 1, 2, ...",2.785714,117
42,При проектировании и строительстве многопролёт...,При:\n● проектировании многоопорных пролетных ...,-30.380385,-41.004524,25.840769,22.763333,30.627643,22.829086,25.249538,29.645643,...,4.789141,4.130608,87.538462,90.238095,"[1, 11, 1, 2, 1, 2, 3, 1, 1, 4, 1, 1, 1, 1, 2,...",3.125000,175,"[2, 1, 3, 2, 1, 3, 1, 5, 1, 1, 3, 1, 2, 2, 1, ...",2.698925,251
43,В процессе строительных работ важно контролиро...,При организации строительного производства осо...,-30.917941,-81.057500,23.051176,37.380000,26.524602,43.313329,25.465559,35.737500,...,4.415140,6.288085,93.470588,122.500000,"[1, 3, 1, 2, 1, 1, 1, 2, 1, 4, 1, 8, 1, 1, 1, ...",2.571429,90,"[1, 5, 1, 2, 1, 1, 1, 1, 1, 2, 1, 4, 1, 2, 1, ...",3.240000,162
44,"Избыточный ил оседает на дне камеры, а осветлё...",Избыточное количество ила оседает на дне камер...,4.109324,-9.098333,18.632973,18.410000,24.213746,21.047593,14.416277,16.319889,...,3.767267,3.597271,67.148649,64.777778,"[1, 1, 1, 2, 1, 4, 3, 1, 1, 8, 1, 2, 1, 2, 1, ...",2.953488,127,"[1, 2, 1, 1, 2, 1, 4, 1, 1, 1, 1, 2, 1, 2, 1, ...",2.500000,115
45,Партия продукции считается соответствующей тре...,Партию продукции следует считать: \n● соответс...,-8.836429,-7.718571,19.010000,23.310000,20.735802,21.657712,21.402000,20.857571,...,3.765849,4.289790,74.714286,70.857143,"[2, 1, 1, 1, 1, 8, 7, 6, 1, 2, 1, 2, 1, 12, 1,...",3.193548,99,"[2, 1, 1, 2, 1, 17, 1, 1, 11, 10, 9, 1, 2, 1, ...",5.558824,189
46,Проверку дефектов стекла и качества изготовлен...,Дефекты стекла и качество исполнения (разд. 1;...,14.260000,85.566769,18.010000,2.325787,22.104253,5.722596,14.646214,-4.660995,...,3.636103,0.941601,74.571429,32.976483,"[6, 1, 1, 1, 2, 1, 1, 2, 2, 1, 3, 1, 2, 1, 1, ...",2.934783,270,"[1, 1, 3, 1, 1, 2, 7, 2, 1, 1, 1, 2, 1, 2, 1, ...",5.343915,1010
47,Для проверки герметичности стаканчиков для взв...,Для проверки герметичности конусов стаканчиков...,-21.506304,-29.345435,30.966522,32.062174,35.365470,36.453841,25.410826,26.635609,...,4.662951,4.879833,96.000000,100.347826,"[1, 7, 1, 1, 1, 3, 2, 1, 1, 2, 2, 1, 3, 1, 2, ...",5.075472,269,"[1, 1, 1, 1, 1, 5, 1, 3, 1, 1, 10, 11, 1, 1, 8...",4.066667,244
48,Прибор предназначен для прямого и косвенного п...,Предназначен для потенциометрического измерени...,-15.992500,-80.250965,21.920000,42.678421,27.251376,51.552929,21.833000,34.589202,...,4.260873,6.222574,77.500000,123.666667,"[1, 5, 4, 1, 2, 1, 6, 1, 1, 2, 1, 1, 5, 1, 7, ...",3.627451,185,"[2, 1, 3, 2, 1, 3, 3, 1, 1, 4, 1, 1, 3, 1, 2, ...",4.013158,305
49,"Если возможно появление нагрузок, которые могу...","Если возможно возникновение нагрузок, приводящ...",3.962778,-9.706176,19.926667,20.086471,24.213746,23.392787,16.448139,19.512422,...,3.906305,3.980864,73.611111,71.901961,"[1, 20, 1, 1, 2, 1, 3, 1, 1, 2, 1, 2, 1, 3, 1,...",2.980392,152,"[1, 21, 1, 1, 1, 2, 1, 2, 4, 3, 1, 1, 5, 2, 1,...",2.779661,164
50,Приказ об отмене действия нормативного докумен...,Приказ об отмене действия НД является основани...,-35.517632,-44.355244,30.378421,32.568537,38.538481,41.469416,24.756895,27.792207,...,5.071937,5.310386,93.263158,101.975610,"[6, 1, 2, 1, 1, 2, 1, 1, 2, 1, 1, 2, 1, 5, 1, ...",3.422222,154,"[5, 1, 2, 1, 1, 1, 2, 1, 3, 1, 2, 1, 3, 3, 2, ...",3.509091,193

In [ ]:
readability_metrics = ['FRESru', 'FKGLru', 'SMOGru', 'ARIru', 'CLIru', 'TIru', 'LIXru', 'MDDtext', 'TotalDDtext']

for metric in readability_metrics:
    before_col = f'{metric}_before'
    after_col = f'{metric}_after'
    deviation_col = f'{metric}_deviation'

    # Calculate deviation, handling division by zero or near-zero values
    df[deviation_col] = df.apply(
        lambda row: (row[after_col] - row[before_col]) / abs(row[before_col]) if row[before_col] != 0 else None,
        axis=1
    )

display(df.head())

,text_before,text_after,FRESru_before,FRESru_after,FKGLru_before,FKGLru_after,SMOGru_before,SMOGru_after,ARIru_before,ARIru_after,...,TotalDDtext_after,FRESru_deviation,FKGLru_deviation,SMOGru_deviation,ARIru_deviation,CLIru_deviation,TIru_deviation,LIXru_deviation,MDDtext_deviation,TotalDDtext_deviation
0,"ТО подлежат МИ, включая изделия, которые наход...",ТО подлежат медицинские изделия: \n● находящие...,-13.651667,-46.613361,22.123333,29.541967,27.011291,35.365470,19.627962,26.876889,...,334,-2.414481,0.335331,0.309285,0.369316,0.270421,0.235272,0.225605,-0.009299,0.084416
1,Испытательное давление для стальных трубопрово...,Испытательные давления для стальных трубопрово...,46.923000,48.895870,14.718000,13.805652,19.770951,19.770951,5.269300,4.261935,...,68,0.042045,-0.061989,0.000000,-0.191176,-0.128158,-0.021109,0.001775,-0.160494,-0.190476
2,Если техническое обслуживание выполняется собс...,В случае исполнения работ по ТО собственной сл...,-31.169237,-14.148766,27.065085,27.550909,32.485404,33.081483,25.617123,20.083406,...,427,0.546066,0.017950,0.018349,-0.216016,-0.324054,-0.076493,-0.054800,0.169538,0.593284
3,"После ремонта средства измерений (МИ), который...","Должен быть проведен КТС (либо поверка, в случ...",-53.906176,-5.737109,37.086471,19.319524,40.516003,22.829086,31.136088,19.788847,...,170,0.893572,-0.479068,-0.436542,-0.364440,-0.136996,-0.300925,-0.389912,-0.305890,-0.317269
4,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО ме...,-19.523929,-46.116266,24.960000,32.337215,28.649668,36.986018,21.528286,26.157725,...,316,-1.362038,0.295562,0.290975,0.215040,0.090208,0.170881,0.107840,0.223873,0.805714

In [ ]:
df.to_excel('df.xlsx', index=False)

In [ ]:
#!pip install ruTS

In [ ]:
!pip install bert_score

Requirement already satisfied: bert_score in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: torch>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from bert_score) (2.8.0+cu126)
Requirement already satisfied: pandas>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from bert_score) (2.2.2)
Requirement already satisfied: transformers>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from bert_score) (4.57.1)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from bert_score) (2.0.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from bert_score) (2.32.4)
Requirement already satisfied: tqdm>=4.31.1 in /usr/local/lib/python3.12/dist-packages (from bert_score) (4.67.1)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (from bert_score) (3.10.0)
Requirement already satisfied: packaging>=20.9 in /usr/local/lib/python3.12/dist-packages (from bert_score) (25.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert_score) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert_score) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.0.1->bert_score) (2025.2)
Requirement already satisfied: filelock in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.20.0)
Requirement already satisfied: typing-extensions>=4.10.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (4.15.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (1.13.3)
Requirement already satisfied: networkx in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.5)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.1.6)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (2025.3.0)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.6.80 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.80)
Requirement already satisfied: nvidia-cudnn-cu12==9.10.2.21 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (9.10.2.21)
Requirement already satisfied: nvidia-cublas-cu12==12.6.4.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.4.1)
Requirement already satisfied: nvidia-cufft-cu12==11.3.0.4 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (11.3.0.4)
Requirement already satisfied: nvidia-curand-cu12==10.3.7.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (10.3.7.77)
Requirement already satisfied: nvidia-cusolver-cu12==11.7.1.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (11.7.1.2)
Requirement already satisfied: nvidia-cusparse-cu12==12.5.4.2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.5.4.2)
Requirement already satisfied: nvidia-cusparselt-cu12==0.7.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (0.7.1)
Requirement already satisfied: nvidia-nccl-cu12==2.27.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (2.27.3)
Requirement already satisfied: nvidia-nvtx-cu12==12.6.77 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.77)
Requirement already satisfied: nvidia-nvjitlink-cu12==12.6.85 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (12.6.85)
Requirement already satisfied: nvidia-cufile-cu12==1.11.1.6 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (1.11.1.6)
Requirement already satisfied: triton==3.4.0 in /usr/local/lib/python3.12/dist-packages (from torch>=1.0.0->bert_score) (3.4.0)
Requirement already satisfied: huggingface-hub<1.0,>=0.34.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score) (0.36.0)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score) (6.0.3)
Requirement already satisfied: regex!=2019.12.17 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score) (2024.11.6)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score) (0.22.1)
Requirement already satisfied: safetensors>=0.4.3 in /usr/local/lib/python3.12/dist-packages (from transformers>=3.0.0->bert_score) (0.6.2)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (1.4.9)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib->bert_score) (3.2.5)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->bert_score) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->bert_score) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->bert_score) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->bert_score) (2025.10.5)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<1.0,>=0.34.0->transformers>=3.0.0->bert_score) (1.2.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas>=1.0.1->bert_score) (1.17.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.0.0->bert_score) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.0.0->bert_score) (3.0.3)

In [ ]:
from bert_score import score

# Calculate BERTScore
# Setting lang='ru' for Russian language
P, R, F1 = score(df['text_after'].tolist(), df['text_before'].tolist(), lang='ru', verbose=True)

# Add the F1 scores to the DataFrame as it is a commonly used metric for BERTScore
df['BERTScore_F1'] = F1.tolist()

# You can also add Precision and Recall if needed
# df['BERTScore_P'] = P.tolist()
# df['BERTScore_R'] = R.tolist()

display(df.head())

calculating scores...
computing bert embedding.

  0%|          | 0/2 [00:00<?, ?it/s]

computing greedy matching.

  0%|          | 0/1 [00:00<?, ?it/s]

done in 138.71 seconds, 0.37 sentences/sec

,text_before,text_after,FRESru_before,FRESru_after,FKGLru_before,FKGLru_after,SMOGru_before,SMOGru_after,ARIru_before,ARIru_after,...,FRESru_deviation,FKGLru_deviation,SMOGru_deviation,ARIru_deviation,CLIru_deviation,TIru_deviation,LIXru_deviation,MDDtext_deviation,TotalDDtext_deviation,BERTScore_F1
0,"ТО подлежат МИ, включая изделия, которые наход...",ТО подлежат медицинские изделия: \n● находящие...,-13.651667,-46.613361,22.123333,29.541967,27.011291,35.365470,19.627962,26.876889,...,-2.414481,0.335331,0.309285,0.369316,0.270421,0.235272,0.225605,-0.009299,0.084416,0.886535
1,Испытательное давление для стальных трубопрово...,Испытательные давления для стальных трубопрово...,46.923000,48.895870,14.718000,13.805652,19.770951,19.770951,5.269300,4.261935,...,0.042045,-0.061989,0.000000,-0.191176,-0.128158,-0.021109,0.001775,-0.160494,-0.190476,0.904063
2,Если техническое обслуживание выполняется собс...,В случае исполнения работ по ТО собственной сл...,-31.169237,-14.148766,27.065085,27.550909,32.485404,33.081483,25.617123,20.083406,...,0.546066,0.017950,0.018349,-0.216016,-0.324054,-0.076493,-0.054800,0.169538,0.593284,0.790718
3,"После ремонта средства измерений (МИ), который...","Должен быть проведен КТС (либо поверка, в случ...",-53.906176,-5.737109,37.086471,19.319524,40.516003,22.829086,31.136088,19.788847,...,0.893572,-0.479068,-0.436542,-0.364440,-0.136996,-0.300925,-0.389912,-0.305890,-0.317269,0.823961
4,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО ме...,-19.523929,-46.116266,24.960000,32.337215,28.649668,36.986018,21.528286,26.157725,...,-1.362038,0.295562,0.290975,0.215040,0.090208,0.170881,0.107840,0.223873,0.805714,0.794504

In [ ]:
import pandas as pd
import nltk
from nltk.corpus import stopwords
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
import spacy

# Загрузка русского языка для spaCy
try:
    nlp = spacy.load("ru_core_news_sm")
except OSError:
    print("Скачивание модели 'ru_core_news_sm' для spaCy...")
    from spacy.cli import download
    download("ru_core_news_sm")
    nlp = spacy.load("ru_core_news_sm")

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [ ]:
# Метрики Семантической Сохранности

def calculate_semantic_similarity(text1, text2):
    """
    Вычисляет косинусное сходство между двумя текстами, используя TF-IDF.
    """
    if not text1 or not text2:
        return 0.0

    vectorizer = TfidfVectorizer()
    try:
        # Создаем матрицу признаков для обоих текстов
        tfidf_matrix = vectorizer.fit_transform([text1, text2])
        # Вычисляем косинусное сходство
        similarity = cosine_similarity(tfidf_matrix[0:1], tfidf_matrix[1:2])[0][0]
        return similarity
    except ValueError:
        # Если один из текстов пустой или содержит только стоп-слова,
        # TF-IDF может вызвать ошибку. В этом случае считаем сходство 0.
        return 0.0

df['semantic_similarity'] = df.apply(
    lambda row: calculate_semantic_similarity(row['text_before'], row['text_after']),
    axis=1
)

# Метрики Упрощения

stop_words = set(stopwords.words('russian'))

def calculate_simplification_metrics(text_before, text_after):
    """
    Вычисляет метрики упрощения: среднюю длину слова, среднюю длину предложения,
    и долю редких слов.
    """
    metrics = {}

    # 1. Средняя длина слова
    words_before = nltk.word_tokenize(text_before.lower())
    words_after = nltk.word_tokenize(text_after.lower())

    if words_before:
        metrics['avg_word_length_before'] = sum(len(word) for word in words_before) / len(words_before)
    else:
        metrics['avg_word_length_before'] = 0

    if words_after:
        metrics['avg_word_length_after'] = sum(len(word) for word in words_after) / len(words_after)
    else:
        metrics['avg_word_length_after'] = 0

    # 2. Средняя длина предложения
    sentences_before = nltk.sent_tokenize(text_before)
    sentences_after = nltk.sent_tokenize(text_after)

    if sentences_before:
        metrics['avg_sentence_length_before'] = len(words_before) / len(sentences_before)
    else:
        metrics['avg_sentence_length_before'] = 0

    if sentences_after:
        metrics['avg_sentence_length_after'] = len(words_after) / len(sentences_after)
    else:
        metrics['avg_sentence_length_after'] = 0

    # 3. Доля редких слов (слова, не являющиеся стоп-словами)
    num_non_stopwords_before = sum(1 for word in words_before if word not in stop_words)
    num_non_stopwords_after = sum(1 for word in words_after if word not in stop_words)

    if words_before:
        metrics['non_stopword_ratio_before'] = num_non_stopwords_before / len(words_before)
    else:
        metrics['non_stopword_ratio_before'] = 0

    if words_after:
        metrics['non_stopword_ratio_after'] = num_non_stopwords_after / len(words_after)
    else:
        metrics['non_stopword_ratio_after'] = 0

    # 4. Упрощение синтаксиса (используя spaCy)
    # Считаем среднюю глубину синтаксического дерева (упрощенный показатель)
    # или количество зависимостей.
    doc_before = nlp(text_before)
    doc_after = nlp(text_after)

    metrics['dependency_count_before'] = len(list(doc_before.sents))
    metrics['dependency_count_after'] = len(list(doc_after.sents))

    subordinating_conjunctions_before = sum(1 for token in doc_before if token.dep_ == 'mark')
    subordinating_conjunctions_after = sum(1 for token in doc_after if token.dep_ == 'mark')

    metrics['subordinating_conjunctions_before'] = subordinating_conjunctions_before
    metrics['subordinating_conjunctions_after'] = subordinating_conjunctions_after

    return pd.Series(metrics)

# Применяем функцию к DataFrame
simplification_metrics = df.apply(
    lambda row: calculate_simplification_metrics(row['text_before'], row['text_after']),
    axis=1
)

# Объединяем результаты с основным DataFrame
df = pd.concat([df, simplification_metrics], axis=1)

In [ ]:
df

,text_before,text_after,FRESru_before,FRESru_after,FKGLru_before,FKGLru_after,SMOGru_before,SMOGru_after,ARIru_before,ARIru_after,...,avg_word_length_before,avg_word_length_after,avg_sentence_length_before,avg_sentence_length_after,non_stopword_ratio_before,non_stopword_ratio_after,dependency_count_before,dependency_count_after,subordinating_conjunctions_before,subordinating_conjunctions_after
0,"ТО подлежат МИ, включая изделия, которые наход...",ТО подлежат медицинские изделия: \n● находящие...,-13.651667,-46.613361,22.123333,29.541967,27.011291,35.365470,19.627962,26.876889,...,6.168831,6.121951,25.666667,41.000000,0.714286,0.768293,3.0,2.0,0.0,0.0
1,Испытательное давление для стальных трубопрово...,Испытательные давления для стальных трубопрово...,46.923000,48.895870,14.718000,13.805652,19.770951,19.770951,5.269300,4.261935,...,4.807692,4.600000,26.000000,25.000000,0.846154,0.840000,1.0,1.0,0.0,0.0
2,Если техническое обслуживание выполняется собс...,В случае исполнения работ по ТО собственной сл...,-31.169237,-14.148766,27.065085,27.550909,32.485404,33.081483,25.617123,20.083406,...,6.782609,5.670330,34.500000,91.000000,0.855072,0.758242,2.0,1.0,1.0,0.0
3,"После ремонта средства измерений (МИ), который...","Должен быть проведен КТС (либо поверка, в случ...",-53.906176,-5.737109,37.086471,19.319524,40.516003,22.829086,31.136088,19.788847,...,6.467742,5.968254,62.000000,21.000000,0.790323,0.809524,1.0,3.0,1.0,1.0
4,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО ме...,-19.523929,-46.116266,24.960000,32.337215,28.649668,36.986018,21.528286,26.157725,...,6.460317,6.527473,31.500000,45.500000,0.809524,0.780220,2.0,2.0,1.0,1.0
5,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО в ...,-45.947353,-67.870072,30.562941,27.685362,31.878182,28.421397,29.129353,34.500130,...,7.025000,7.516129,40.000000,20.666667,0.875000,0.951613,1.0,3.0,0.0,0.0
6,"Прибор, установку или оборудование, подготовле...",Необходимо проверить перед включением: \n● при...,-45.841923,-73.092273,23.863846,30.537273,23.392787,31.878182,25.575731,31.755545,...,6.705882,7.103448,17.000000,29.000000,0.823529,0.862069,1.0,1.0,0.0,0.0
7,"Растворы щелочей, концентрированных кислот и а...",Приготавливать растворы разрешается только:\n●...,7.613125,22.795215,17.347500,13.421828,17.684018,13.507325,17.072375,17.899790,...,6.305556,5.690476,18.000000,14.000000,0.777778,0.857143,2.0,3.0,0.0,0.0
8,Легковоспламеняющиеся и горючие жидкости необх...,ЛВЖ и ГЖ должны храниться: \n● в лабораторных ...,-20.389000,11.575000,24.126000,21.250000,26.524602,23.392787,21.294900,15.978333,...,6.571429,4.875000,28.000000,40.000000,0.785714,0.825000,1.0,1.0,0.0,0.0
9,Основным источником травм при работе со стекля...,"Основным травмирующим фактором, связанным с ис...",-1.279286,-21.828636,22.410000,26.873636,25.007769,27.959265,17.280429,22.795288,...,5.781250,5.926829,32.000000,41.000000,0.812500,0.878049,1.0,1.0,0.0,0.0
10,"Чтобы избежать ожогов кистей и пальцев, посуду...",Следует переносить посуду с горячей жидкостью:...,25.385000,39.739505,17.410000,11.690180,17.684018,15.315303,13.252000,7.949230,...,5.137931,4.460000,29.000000,16.666667,0.758621,0.740000,1.0,3.0,1.0,0.0
11,При получении травмы или любом несчастном случ...,При получении травмы и при каждом несчастном с...,-52.491866,-20.206250,41.981642,28.875000,40.516003,30.627643,28.677082,22.122000,...,5.946667,5.800000,75.000000,47.500000,0.760000,0.789474,1.0,2.0,1.0,3.0
12,"Проверить состояние спецодежды, спецобуви и др...",Выполнить: \n● Проверить исправность спецодежд...,19.776212,23.027857,12.655455,12.010000,13.698865,12.944461,16.907664,19.828714,...,6.121951,5.881356,8.200000,8.428571,0.829268,0.932203,5.0,9.0,1.0,0.0
13,"Все работы, связанные с использованием или воз...",Выполнять все операции:\n● только в вытяжном ш...,-0.763649,-15.752121,19.314054,20.188788,22.541950,22.829086,18.984385,20.450818,...,5.956522,5.313433,23.000000,22.333333,0.826087,0.895522,2.0,3.0,0.0,0.0
14,Под периодом индивидуальных испытаний (далее —...,Под периодом индивидуальных испытаний (именуем...,-65.269762,-125.455667,35.810000,54.726000,40.516003,60.612396,29.628619,45.085500,...,6.607843,6.850000,51.000000,100.000000,0.843137,0.890000,1.0,1.0,0.0,0.0
15,Объем и условия выполнения пусконаладочных раб...,Объем и условия выполнения пусконаладочных раб...,-73.367222,-51.132949,37.896667,32.879231,44.206453,40.030782,34.583833,32.066167,...,7.109091,6.797980,55.000000,49.500000,0.872727,0.878788,1.0,2.0,0.0,0.0
16,Если в рабочей документации нет дополнительных...,Величину испытательного давления на прочность ...,-12.212619,-17.158478,21.710000,19.377391,25.007769,21.657712,21.353357,23.082272,...,6.400000,7.346154,25.000000,13.000000,0.760000,0.807692,1.0,3.0,1.0,0.0
17,Работы по проведению общего опробования включа...,Работы по проведению комплексного опробования ...,-39.797609,-92.120556,33.523043,51.976667,33.081483,43.313329,25.410826,37.355315,...,6.372549,6.368421,51.000000,95.000000,0.784314,0.821053,1.0,1.0,0.0,0.0
18,Звуковой и световой сигнал подает система мони...,Система мониторинга: \n● выдает: \n● звук \n● ...,-10.790926,-32.108478,23.421111,25.127391,27.959265,29.323821,18.730537,24.947152,...,6.000000,5.818182,31.000000,33.000000,0.870968,1.000000,1.0,1.0,0.0,0.0
19,"Не используйте растворители, автомобильные мою...",Не используйте для очистки холодильника: \n● р...,-35.525000,-39.286053,24.650000,24.857368,29.323821,29.323821,26.215000,27.664237,...,6.178571,5.931034,28.000000,29.000000,0.892857,0.931034,1.0,1.0,0.0,0.0
20,При подключении системы к внешним сервисам чер...,В случае интеграции системы с внешними сервиса...,20.699286,-52.417308,17.110000,41.334615,18.756532,37.510645,15.689548,31.012500,...,6.155556,6.492958,22.500000,71.000000,0.800000,0.802817,2.0,1.0,0.0,0.0
21,Если технические условия распространяются на п...,Если ТУ распространяются на продукты двух и бо...,-25.465000,-42.657308,29.610000,31.694615,30.627643,31.878182,22.122000,25.806167,...,5.145455,5.186441,55.000000,59.000000,0.763636,0.796610,1.0,1.0,2.0,3.0
22,Показатели могут отличаться от указанных в зав...,Значения отличаются от приведенных значений в ...,-21.200294,-45.929865,27.104118,31.515405,34.242525,38.538481,21.212294,28.064986,...,5.829268,6.122449,41.000000,49.000000,0.829268,0.918367,1.0,1.0,1.0,0.0
23,После завершения уборки робот-пылесос возвраща...,"После того, как: \n● робот-пылесос закончит уб...",7.881000,-1.793571,16.196000,24.710000,18.756532,19.770951,15.034250,19.378071,...,6.444444,5.666667,13.500000,42.000000,0.777778,0.809524,2.0,3.0,0.0,0.0
24,"Гарантия не действует для котлов, в конструкци...",Гарантия не распространяется на котлы (кроме с...,-33.573824,-40.906935,28.833529,28.903548,31.878182,34.242525,25.999353,27.937435,...,6.463415,6.450000,41.000000,40.000000,0.756098,0.825000,1.0,1.0,0.0,0.0
25,Гарантия не распространяется на повреждения ко...,Гарантия не распространяется: \n● на дефекты к...,-49.909681,-67.037222,35.254681,39.876667,42.401397,46.783635,29.559670,32.911815,...,6.271186,5.828947,59.000000,76.000000,0.796610,0.828947,1.0,2.0,0.0,0.0
26,Контроль качества на всех этапах производства ...,Контроль качества на всех этапах производства ...,-60.074091,-59.349091,32.219091,35.619091,34.242525,34.242525,31.521348,34.227455,...,7.756757,7.000000,37.000000,55.000000,0.810811,0.909091,1.0,1.0,0.0,0.0
27,При выполнении инвазивных процедур необходимо ...,При проведении инвазивных процедур строго собл...,-18.680625,-65.047759,21.022500,31.641034,25.007769,37.510645,22.941125,34.513810,...,6.972973,6.925000,18.500000,40.000000,0.864865,0.925000,2.0,1.0,0.0,0.0
28,Для технологии MIMO (Multiple Input Multiple O...,Для MIMO (Multiple Input Multiple Output) важн...,-36.128636,-37.494545,32.373636,32.564545,34.242525,35.365470,30.955182,32.520182,...,6.032787,6.245902,61.000000,61.000000,0.918033,0.934426,1.0,1.0,0.0,0.0
29,Исследование стабильности бактериальных штаммо...,Исследование стабильности бактериальных штаммо...,-20.255541,-46.012143,22.038378,25.320000,26.524602,27.959265,25.582764,29.851036,...,7.357143,7.666667,21.000000,21.000000,0.785714,0.880952,2.0,2.0,0.0,0.0
30,Для стабильной передачи данных в распределённы...,Для обеспечения устойчивой передачи данных в р...,4.109324,-17.143947,18.632973,21.762632,23.392787,27.251376,18.815196,22.557395,...,6.404762,5.903846,21.000000,26.000000,0.857143,0.923077,2.0,2.0,0.0,0.0
31,Наличие источников тепла рядом с местом устано...,"Наличие источников, излучающих тепло в непосре...",-10.773000,-21.527069,22.782000,25.558276,27.959265,31.878182,18.540500,22.209672,...,5.677419,6.000000,31.000000,36.000000,0.870968,0.861111,1.0,1.0,0.0,0.0
32,Для безопасной работы оборудования при превыше...,Для обеспечения безопасности работы оборудован...,-25.197000,-44.518333,24.798000,29.090000,29.323821,35.365470,22.046100,25.159667,...,6.888889,7.030303,27.000000,33.000000,0.777778,0.787879,1.0,1.0,0.0,2.0
33,"Нажмите кнопку питания, чтобы включить аэрофри...","Нажмите кнопку питания, чтобы включить аэрофри...",51.097500,61.478605,9.360000,8.147791,13.981255,13.981255,6.664500,4.148863,...,4.705882,4.152542,12.750000,14.750000,0.784314,0.762712,4.0,4.0,3.0,3.0
34,При подготовке рабочей документации следует уч...,При составлении рабочей документации необходим...,-26.967500,-76.410902,29.820000,43.414918,34.242525,47.611705,23.530500,33.790172,...,6.386364,6.315789,44.000000,76.000000,0.772727,0.815789,1.0,1.0,0.0,0.0
35,"Чтобы повысить удобство работы с устройством, ...","Чтобы улучшить взаимодействие с пользователем,...",12.201129,10.262419,16.547097,16.818065,18.756532,19.770951,15.916137,18.339363,...,5.864865,5.974359,18.500000,19.500000,0.729730,0.794872,2.0,2.0,2.0,2.0
36,В режиме ожидания поверните регулятор и выбери...,В режиме ожидания поверните головку регулятора...,17.029697,1.563571,15.606970,15.010000,18.405973,14.179520,12.768091,14.612048,...,5.607843,5.865385,17.000000,7.428571,0.725490,0.807692,3.0,7.0,2.0,3.0
37,Фактические значения могут отличаться от указа...,Значения отличаются от приведенных значений в ...,-20.265000,-37.853571,27.610000,29.750000,34.242525,36.453841,20.965222,26.353500,...,5.767442,5.914894,43.000000,47.000000,0.813953,0.914894,1.0,1.0,1.0,0.0
38,Чтобы очистить внутреннюю поверхность аэрофрит...,Для удаления пятен с внутренней стороны аэрофр...,37.085000,16.519762,12.910000,14.723333,12.505699,16.931307,13.440167,14.621643,...,5.794118,6.050000,17.000000,13.333333,0.823529,0.825000,2.0,3.0,2.0,1.0
39,Если вы планируете использовать баллоны со сжи...,Кухонную плиту не следует устанавливать: \n● е...,39.845000,1.175541,13.320000,24.931622,16.542113,25.007769,8.388179,17.575257,...,4.950000,5.200000,20.000000,45.000000,0.700000,0.822222,2.0,1.0,2.0,3.0
40,Ножной тормоз должен обеспечивать полный возвр...,Работа ножного тормоза должна обеспечивать пол...,19.268333,-6.721667,17.310000,21.420000,21.657712,25.007769,12.708595,17.421917,...,5.630435,5.777778,23.000000,27.000000,0.739130,0.833333,2.0,2.0,0.0,0.0
41,Когда в баке заканчивается резервный запас или...,При каждом включении зажигания на панели прибо...,1.744677,-16.538684,22.942258,27.725789,25.007769,30.627643,17.234855,21.297421,...,6.000000,6.000000,33.000000,43.000000,0.757576,0.790698,1.0,1.0,1.0,1.0
42,При проектировании и строительстве многопролёт...,При:\n● проектировании многоопорных пролетных ...,-30.380385,-41.004524,25.840769,22.763333,30.627643,22.829086,25.249538,29.645643,...,7.120690,7.085106,29.000000,15.666667,0.775862,0.904255,2.0,6.0,0.0,0.0
43,В процессе строительных работ важно контролиро...,При организации строительного производства осо...,-30.917941,-81.057500,23.051176,37.380000,26.524602,43.313329,25.465559,35.737500,...,7.675676,7.176471,18.500000,51.000000,0.864865,0.921569,2.0,1.0,0.0,0.0
44,"Избыточный ил оседает на дне камеры, а осветлё...",Избыточное количество ила оседает на дне камер...,4.109324,-9.098333,18.632973,18.410000,24.213746,21.047593,14.416277,16.319889,...,5.466667,5.617021,22.500000,15.666667,0.822222,0.872340,2.0,3.0,0.0,0.0
45,Партия продукции считается соответствующей тре...,Партию продукции следует считать: \n● соответс...,-8.836429,-7.718571,19.010000,23.310000,20.735802,21.657712,21.402000,20.857571,...,6.906250,5.828571,16.000000,35.000000,0.812500,0.828571,2.0,1.0,2.0,2.0
46,Проверку дефектов стекла и качества изготовлен...,Дефекты стекла и качество исполнения (разд. 1;...,14.260000,85.566769,18.010000,2.325787,22.104253,5.722596,14.646214,-4.660995,...,5.849462,4.030303,23.250000,15.230769,0.774194,0.919192,4.0,8.0,1.0,1.0
47,Для проверки герметичности стаканчиков для взв...,Для проверки герметичности конусов стаканчиков...,-21.506304,-29.345435,30.966522,32.062174,35.365470,36.453841,25.410826,26.635609,...,6.074074,5.672131,54.000000,61.000000,0.814815,0.852459,1.0,1.0,0.0,0.0
48,Прибор предназначен для прямого и косвенного п...,Предназначен для потенциометрического измерени...,-15.992500,-80.250965,21.920000,42.678421,27.251376,51.552929,21.833000,34.589202,...,6.280000,6.293333,25.000000,75.000000,0.840000,0.893333,2.0,1.0,0.0,0.0
49,"Если возможно появление нагрузок, которые могу...","Если возможно возникновение нагрузок, приводящ...",3.962778,-9.706176,19.926667,20.086471,24.213746,23.392787,16.448139,19.512422,...,5.826923,6.193548,26.000000,20.666667,0.730769,0.774194,2.0,3.0,2.0,3.0
50,Приказ об отмене действия нормативного докумен...,Приказ об отмене действия НД является основани...,-35.517632,-44.355244,30.378421,32.568537,38.538481,41.469416,24.756895,27.792207,...,6.130435,5.803571,46.000000,56.000000,0.782609,0.857143,1.0,1.0,0.0,0.0

In [ ]:
# Создайте список столбцов в нужном порядке
new_column_order = ['text_before', 'text_after', 'FRESru_before', 'FRESru_after', 'FRESru_deviation', 'FKGLru_before', 'FKGLru_after', 'FKGLru_deviation', 'SMOGru_before', 'SMOGru_after', 'SMOGru_deviation', 'ARIru_before', 'ARIru_after', 'ARIru_deviation', 'CLIru_before', 'CLIru_after', 'CLIru_deviation', 'TIru_before', 'TIru_after', 'TIru_deviation', 'LIXru_before', 'LIXru_after', 'LIXru_deviation', 'DDtext_before', 'MDDtext_before', 'DDtext_after', 'MDDtext_after', 'MDDtext_deviation','TotalDDtext_before','TotalDDtext_after','TotalDDtext_deviation','BERTScore_F1']
# Переиндексируйте DataFrame, используя новый порядок столбцов
df = df[new_column_order]

# Выведите первые несколько строк DataFrame с новым порядком столбцов
display(df.head(30))

,text_before,text_after,FRESru_before,FRESru_after,FRESru_deviation,FKGLru_before,FKGLru_after,FKGLru_deviation,SMOGru_before,SMOGru_after,...,LIXru_deviation,DDtext_before,MDDtext_before,DDtext_after,MDDtext_after,MDDtext_deviation,TotalDDtext_before,TotalDDtext_after,TotalDDtext_deviation,BERTScore_F1
0,"ТО подлежат МИ, включая изделия, которые наход...",ТО подлежат медицинские изделия: \n● находящие...,-13.651667,-46.613361,-2.414481,22.123333,29.541967,0.335331,27.011291,35.365470,...,0.225605,"[1, 1, 1, 2, 1, 2, 1, 3, 1, 2, 2, 1, 11, 2, 1,...",4.162162,"[1, 1, 2, 2, 1, 3, 1, 2, 2, 1, 10, 2, 1, 3, 2,...",4.123457,-0.009299,308,334,0.084416,0.886535
1,Испытательное давление для стальных трубопрово...,Испытательные давления для стальных трубопрово...,46.923000,48.895870,0.042045,14.718000,13.805652,-0.061989,19.770951,19.770951,...,0.001775,"[1, 11, 2, 1, 3, 1, 5, 1, 2, 1, 1, 5, 1, 1, 2,...",3.000000,"[1, 11, 2, 1, 3, 1, 5, 1, 2, 1, 4, 5, 3, 1, 1,...",2.518519,-0.160494,84,68,-0.190476,0.904063
2,Если техническое обслуживание выполняется собс...,В случае исполнения работ по ТО собственной сл...,-31.169237,-14.148766,0.546066,27.065085,27.550909,0.017950,32.485404,33.081483,...,-0.054800,"[3, 1, 1, 8, 1, 2, 1, 2, 3, 1, 1, 1, 1, 1, 2, ...",3.884058,"[1, 11, 1, 1, 1, 2, 1, 6, 1, 1, 2, 1, 1, 2, 3,...",4.542553,0.169538,268,427,0.593284,0.790718
3,"После ремонта средства измерений (МИ), который...","Должен быть проведен КТС (либо поверка, в случ...",-53.906176,-5.737109,0.893572,37.086471,19.319524,-0.479068,40.516003,22.829086,...,-0.389912,"[1, 15, 14, 1, 1, 2, 1, 2, 1, 6, 1, 3, 2, 1, 4...",4.081967,"[1, 2, 1, 2, 1, 3, 5, 4, 1, 2, 1, 6, 1, 2, 1, ...",2.833333,-0.305890,249,170,-0.317269,0.823961
4,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО ме...,-19.523929,-46.116266,-1.362038,24.960000,32.337215,0.295562,28.649668,36.986018,...,0.107840,"[8, 1, 1, 1, 1, 2, 1, 4, 1, 1, 2, 1, 4, 3, 1, ...",2.868852,"[7, 1, 1, 1, 3, 1, 2, 2, 1, 3, 4, 1, 2, 1, 5, ...",3.511111,0.223873,175,316,0.805714,0.794504
5,Контроль качества работы системы технического ...,Оценку качества функционирования системы ТО в ...,-45.947353,-67.870072,-0.477127,30.562941,27.685362,-0.094153,31.878182,28.421397,...,-0.015063,"[9, 1, 1, 1, 1, 2, 2, 1, 6, 1, 2, 1, 2, 4, 1, ...",3.384615,"[8, 1, 1, 1, 4, 2, 1, 1, 1, 1, 2, 1, 5, 1, 2, ...",3.065574,-0.094262,132,187,0.416667,0.779594
6,"Прибор, установку или оборудование, подготовле...",Необходимо проверить перед включением: \n● при...,-45.841923,-73.092273,-0.594442,23.863846,30.537273,0.279646,23.392787,31.878182,...,0.148888,"[12, 1, 2, 1, 4, 1, 2, 1, 1, 2, 3, 5, 1, 1, 2, 4]",2.687500,"[1, 1, 2, 2, 1, 3, 2, 1, 3, 1, 1, 2, 1, 4, 2, ...",1.964286,-0.269103,43,55,0.279070,0.790449
7,"Растворы щелочей, концентрированных кислот и а...",Приготавливать растворы разрешается только:\n●...,7.613125,22.795215,1.994199,17.347500,13.421828,-0.226296,17.684018,13.507325,...,0.035824,"[7, 1, 2, 1, 3, 1, 5, 1, 3, 2, 1, 4, 2, 1, 3, ...",2.970588,"[2, 1, 4, 3, 1, 1, 5, 1, 1, 2, 1, 5, 2, 1, 3, ...",2.585366,-0.129679,101,106,0.049505,0.807411
8,Легковоспламеняющиеся и горючие жидкости необх...,ЛВЖ и ГЖ должны храниться: \n● в лабораторных ...,-20.389000,11.575000,1.567708,24.126000,21.250000,-0.119207,26.524602,23.392787,...,-0.211470,"[3, 1, 2, 1, 1, 1, 2, 3, 2, 1, 6, 1, 2, 1, 2, ...",2.777778,"[3, 1, 2, 1, 4, 1, 2, 1, 26, 1, 1, 3, 7, 1, 5,...",4.589744,0.652308,75,179,1.386667,0.776166
9,Основным источником травм при работе со стекля...,"Основным травмирующим фактором, связанным с ис...",-1.279286,-21.828636,-16.063144,22.410000,26.873636,0.199181,25.007769,27.959265,...,0.200078,"[1, 11, 1, 1, 3, 2, 1, 3, 1, 2, 1, 4, 1, 2, 1,...",2.677419,"[2, 1, 12, 1, 2, 1, 2, 1, 2, 1, 2, 1, 4, 9, 3,...",3.075000,0.148494,83,123,0.481928,0.861308
10,"Чтобы избежать ожогов кистей и пальцев, посуду...",Следует переносить посуду с горячей жидкостью:...,25.385000,39.739505,0.565472,17.410000,11.690180,-0.328536,17.684018,15.315303,...,-0.277130,"[1, 10, 1, 1, 1, 2, 5, 4, 2, 1, 3, 1, 1, 2, 1,...",2.964286,"[1, 1, 2, 1, 3, 4, 1, 2, 1, 5, 1, 1, 2, 1, 1, ...",3.081633,0.039587,83,151,0.819277,0.810020
11,При получении травмы или любом несчастном случ...,При получении травмы и при каждом несчастном с...,-52.491866,-20.206250,0.615059,41.981642,28.875000,-0.312199,40.516003,30.627643,...,-0.218686,"[1, 9, 1, 3, 2, 1, 5, 3, 1, 2, 1, 2, 1, 2, 1, ...",4.054054,"[1, 11, 1, 9, 3, 2, 1, 5, 4, 1, 2, 1, 1, 2, 3,...",2.723404,-0.328227,300,256,-0.146667,0.828198
12,"Проверить состояние спецодежды, спецобуви и др...",Выполнить: \n● Проверить исправность спецодежд...,19.776212,23.027857,0.164422,12.655455,12.010000,-0.051002,13.698865,12.944461,...,0.250391,"[1, 1, 1, 2, 2, 1, 5, 1, 2, 1, 11, 1, 13, 1, 2...",2.666667,"[2, 1, 3, 1, 1, 1, 2, 1, 2, 10, 1, 1, 1, 1, 3,...",2.169811,-0.186321,96,115,0.197917,0.816100
13,"Все работы, связанные с использованием или воз...",Выполнять все операции:\n● только в вытяжном ш...,-0.763649,-15.752121,-19.627446,19.314054,20.188788,0.045290,22.541950,22.829086,...,0.027105,"[1, 20, 1, 2, 1, 2, 2, 1, 3, 5, 1, 2, 1, 4, 6,...",3.250000,"[1, 2, 5, 1, 3, 2, 1, 6, 1, 3, 2, 1, 5, 1, 1, ...",2.910448,-0.104478,143,195,0.363636,0.777656
14,Под периодом индивидуальных испытаний (далее —...,Под периодом индивидуальных испытаний (именуем...,-65.269762,-125.455667,-0.922110,35.810000,54.726000,0.528232,40.516003,60.612396,...,0.389571,"[1, 9, 1, 2, 4, 3, 1, 1, 5, 1, 1, 1, 2, 3, 1, ...",2.860000,"[1, 10, 1, 2, 5, 4, 1, 2, 1, 6, 1, 1, 2, 1, 3,...",3.882353,0.357466,143,396,1.769231,0.817096
15,Объем и условия выполнения пусконаладочных раб...,Объем и условия выполнения пусконаладочных раб...,-73.367222,-51.132949,0.303055,37.896667,32.879231,-0.132398,44.206453,40.030782,...,-0.083452,"[27, 1, 2, 1, 1, 2, 1, 7, 1, 1, 1, 2, 1, 6, 13...",3.629630,"[6, 1, 2, 1, 1, 2, 1, 2, 1, 1, 2, 2, 1, 3, 1, ...",2.805825,-0.226967,196,289,0.474490,0.767038
16,Если в рабочей документации нет дополнительных...,Величину испытательного давления на прочность ...,-12.212619,-17.158478,-0.404979,21.710000,19.377391,-0.107444,25.007769,21.657712,...,-0.025707,"[4, 2, 1, 1, 15, 1, 2, 1, 11, 1, 2, 1, 2, 1, 2...",2.666667,"[12, 1, 2, 1, 2, 1, 6, 1, 2, 2, 1, 3, 1, 3, 1,...",2.615385,-0.019231,64,68,0.062500,0.816142
17,Работы по проведению общего опробования включа...,Работы по проведению комплексного опробования ...,-39.797609,-92.120556,-1.314726,33.523043,51.976667,0.550476,33.081483,43.313329,...,0.360822,"[5, 1, 2, 1, 2, 1, 1, 2, 1, 4, 1, 2, 1, 2, 1, ...",3.280000,"[5, 1, 2, 1, 2, 2, 1, 3, 1, 2, 1, 2, 2, 1, 3, ...",3.406250,0.038491,164,327,0.993902,0.776329
18,Звуковой и световой сигнал подает система мони...,Система мониторинга: \n● выдает: \n● звук \n● ...,-10.790926,-32.108478,-1.975507,23.421111,25.127391,0.072852,27.959265,29.323821,...,0.028926,"[3, 1, 2, 1, 1, 1, 3, 2, 1, 5, 1, 2, 1, 1, 3, ...",3.033333,"[14, 1, 2, 1, 10, 2, 1, 7, 1, 1, 4, 1, 1, 1, 1...",2.687500,-0.114011,91,86,-0.054945,0.791483
19,"Не используйте растворители, автомобильные мою...",Не используйте для очистки холодильника: \n● р...,-35.525000,-39.286053,-0.105871,24.650000,24.857368,0.008413,29.323821,29.323821,...,0.029825,"[1, 1, 3, 2, 1, 4, 1, 6, 2, 1, 9, 3, 2, 1, 13,...",4.888889,"[1, 1, 2, 1, 2, 1, 6, 1, 2, 1, 4, 1, 6, 1, 1, ...",2.857143,-0.415584,132,80,-0.393939,0.882919
20,При подключении системы к внешним сервисам чер...,В случае интеграции системы с внешними сервиса...,20.699286,-52.417308,-3.532324,17.110000,41.334615,1.415816,18.756532,37.510645,...,0.590547,"[1, 8, 1, 2, 1, 4, 1, 6, 1, 1, 1, 2, 1, 1, 2, ...",2.837209,"[1, 9, 1, 1, 2, 1, 3, 1, 6, 1, 2, 1, 27, 1, 2,...",3.042254,0.072270,122,216,0.770492,0.762561
21,Если технические условия распространяются на п...,Если ТУ распространяются на продукты двух и бо...,-25.465000,-42.657308,-0.675135,29.610000,31.694615,0.070402,30.627643,31.878182,...,0.003134,"[3, 1, 1, 15, 1, 2, 3, 1, 2, 4, 3, 1, 1, 4, 1,...",3.814815,"[2, 1, 15, 1, 2, 3, 1, 2, 4, 3, 1, 1, 4, 1, 2,...",4.034483,0.057583,206,234,0.135922,0.845960
22,Показатели могут отличаться от указанных в зав...,Значения отличаются от приведенных значений в ...,-21.200294,-45.929865,-1.166473,27.104118,31.515405,0.162753,34.242525,38.538481,...,0.126520,"[1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 6, 1, ...",3.925000,"[1, 2, 1, 3, 1, 5, 3, 2, 1, 4, 1, 1, 3, 1, 1, ...",2.687500,-0.315287,157,129,-0.178344,0.837674
23,После завершения уборки робот-пылесос возвраща...,"После того, как: \n● робот-пылесос закончит уб...",7.881000,-1.793571,-1.227582,16.196000,24.710000,0.525685,18.756532,19.770951,...,0.251384,"[1, 5, 1, 3, 2, 1, 2, 1, 3, 1, 2, 6, 2, 1, 1, ...",2.740741,"[1, 14, 7, 6, 5, 1, 3, 2, 1, 8, 1, 1, 2, 3, 4,...",3.489362,0.273145,74,164,1.216216,0.857095
24,"Гарантия не действует для котлов, в конструкци...",Гарантия не распространяется на котлы (кроме с...,-33.573824,-40.906935,-0.218418,28.833529,28.903548,0.002428,31.878182,34.242525,...,0.029008,"[2, 1, 1, 2, 5, 1, 3, 1, 1, 6, 1, 2, 1, 4, 1, ...",3.325000,"[2, 1, 1, 2, 2, 1, 3, 1, 1, 2, 1, 1, 2, 7, 1, ...",2.410256,-0.275111,133,94,-0.293233,0.819985
25,Гарантия не распространяется на повреждения ко...,Гарантия не распространяется: \n● на дефекты к...,-49.909681,-67.037222,-0.343171,35.254681,39.876667,0.131103,42.401397,46.783635,...,0.132229,"[2, 1, 1, 2, 1, 1, 3, 4, 3, 2, 1, 5, 2, 1, 3, ...",3.900000,"[2, 1, 3, 1, 1, 4, 1, 1, 3, 3, 1, 1, 11, 1, 1,...",3.106667,-0.203419,234,233,-0.004274,0.818753
26,Контроль качества на всех этапах производства ...,Контроль качества на всех этапах производства ...,-60.074091,-59.349091,0.012068,32.219091,35.619091,0.105527,34.242525,34.242525,...,0.239587,"[6, 1, 2, 1, 4, 1, 1, 2, 3, 1, 2, 4, 1, 6, 1, ...",4.184211,"[6, 1, 2, 1, 4, 1, 2, 1, 3, 1, 2, 1, 4, 1, 2, ...",4.571429,0.092543,159,256,0.610063,0.814890
27,При выполнении инвазивных процедур необходимо ...,При проведении инвазивных процедур строго собл...,-18.680625,-65.047759,-2.482098,21.022500,31.641034,0.505103,25.007769,37.510645,...,0.277998,"[1, 3, 1, 2, 1, 2, 1, 1, 1, 2, 7, 1, 1, 1, 2, ...",2.800000,"[1, 4, 1, 2, 1, 1, 1, 1, 2, 1, 5, 2, 1, 3, 1, ...",3.538462,0.263736,98,138,0.408163,0.910812
28,Для технологии MIMO (Multiple Input Multiple O...,Для MIMO (Multiple Input Multiple Output) важн...,-36.128636,-37.494545,-0.037807,32.373636,32.564545,0.005897,34.242525,35.365470,...,0.022543,"[1, 8, 1, 1, 2, 1, 2, 3, 4, 1, 1, 2, 1, 4, 3, ...",5.500000,"[1, 7, 1, 2, 1, 2, 3, 4, 1, 2, 1, 3, 1, 4, 3, ...",4.703125,-0.144886,341,301,-0.117302,0.843692
29,Исследование стабильности бактериальных штаммо...,Исследование стабильности бактериальных штаммо...,-20.255541,-46.012143,-1.271583,22.038378,25.320000,0.148905,26.524602,27.959265,...,0.101012,"[10, 1, 1, 2, 1, 2, 1, 2, 1, 4, 1, 1, 1, 2, 1,...",2.675000,"[10, 1, 1, 2, 1, 2, 1, 2, 1, 4, 2, 1, 3, 1, 1,...",2.837209,0.060639,107,122,0.140187,0.908524

In [ ]:
calculate_dd_mdd("Прибор, установку, оборудование, самостоятельно подготовленные обучающимся к работе, необходимо проверить перед включением.")

([12, 1, 2, 1, 4, 2, 1, 3, 1, 1, 2, 4, 1, 1, 2, 4], 2.625, 42)

In [ ]:
calculate_dd_mdd("Прибор, установку, оборудование: самостоятельно подготовленные обучающимся к работе необходимо проверить перед включением.")

([11, 1, 2, 1, 4, 2, 1, 7, 1, 1, 2, 1, 1, 2, 4], 2.7333333333333334, 41)

In [ ]:
df.to_excel('df.xlsx', index=False)